appveyor.yml, tests/sources/test_vector4_impl.h, tests/sources/test_vector4d.cpp, tests/sources/test_vector4d_mix_a.cpp, tests/sources/test_vector4d_mix_b.cpp, tests/sources/test_vector4d_mix_c.cpp, tests/sources/test_vector4d_mix_d.cpp, tests/sources/test_vector4d_mix_w.cpp, tests/sources/test_vector4d_mix_x.cpp, tests/sources/test_vector4d_mix_y.cpp, tests/sources/test_vector4d_mix_z.cpp, tests/sources/test_vector4f_mix_a.cpp, tests/sources/test_vector4f_mix_b.cpp, tests/sources/test_vector4f_mix_c.cpp, tests/sources/test_vector4f_mix_d.cpp, tests/sources/test_vector4f_mix_w.cpp, tests/sources/test_vector4f_mix_x.cpp, tests/sources/test_vector4f_mix_y.cpp, tests/sources/test_vector4f_mix_z.cpp, tools/release_scripts/test_everything.py
This keeps it in sync with the proposed ACL VS2019 changes.
=> chore: restore separate mix tests for faster compilation

includes/rtm/scalarf.h, sonar-project.properties
AppVeyor upgraded the VS2019 compiler which introduced a code generation bug (it has been reported).
Travis updated sonarcloud which caused it to fail because no source files were being analyzed.
=> fix: resolve sonar cloud and VS2019 issues

includes/rtm/angled.h, includes/rtm/anglef.h, includes/rtm/impl/angle_constants.h, tests/sources/test_angle.cpp, tests/sources/test_scalar.cpp
Prior to this change, angle constants were a pain to use properly. We now do something similar
to what boost does.
=> fix(angle): clean up how angle constants are used and add arithmetic operators for angles

includes/rtm/impl/compiler_utils.h, includes/rtm/packing/quatf.h, includes/rtm/scalarf.h, includes/rtm/vector4f.h
Clang defines `_MSC_VER` when compiling with `clang-cl` but fails to compile some MSVC specific syntax. This commit simply adds a `!defined(__clang__)` condition where required.
=> chore: clang-cl fixes

includes/rtm/impl/compiler_utils.h, tools/bench/sources/bench_quat_conjugate.cpp, tools/bench/sources/bench_quat_from_positive_w.cpp, tools/bench/sources/bench_quat_mul.cpp, tools/bench/sources/bench_quat_mul_vector3.cpp, tools/bench/sources/bench_qvv_mul.cpp, tools/bench/sources/bench_scalar_abs.cpp, tools/bench/sources/bench_vector_abs.cpp, tools/bench/sources/bench_vector_sign.cpp
Benchmark numbers were slightly inaccurate at times due to store forwarding penalties. Due to the nature of micro benchmarks, some functions may or may not be as fast as measured. They only serve to give a general idea.
At a later date, RTM will be benchmarked within ACL to get accurate measurements under a real application. Optimal implementations will be selected and added to RTM.
=> fix: avoid store-forwarding penalty when benchmarking

includes/rtm/quatd.h, includes/rtm/quatf.h, includes/rtm/scalard.h, includes/rtm/scalarf.h, includes/rtm/vector4d.h, includes/rtm/vector4f.h, tests/sources/test_quat.cpp, tests/sources/test_scalar.cpp, tests/sources/test_vector4_impl.h
See [here](https://fgiesen.wordpress.com/2012/08/15/linear-interpolation-past-present-and-future/) as well for details. Tested with [ACL](https://github.com/nfrechette/acl/issues/51) and everything is working as intended.
Having a stable lerp by default is more important than the 1-3 cycles saved to avoid a multiplication that can often be fused. If there is a need, it can either be implemented by hand by the user trivially or we can add `vector_lerp_fast` and related variants.
=> fix: lerp should be stable and return start/end exactly when alpha is 0.0/1.0

includes/rtm/impl/scalar_common.h, includes/rtm/impl/vector_common.h, includes/rtm/vector4d.h, includes/rtm/vector4f.h, tests/sources/test_vector4_impl.h
When AVX isn't present, not zeroing requires 2 instructions: load + shuffle.
This ensures all partial load functions are consistent in behavior.
=> fix: partial vector loads zero unused lanes

includes/rtm/scalarf.h
VS2019 16.5.4 fixes the issue, make sure we enable back optimizations for later versions.
Fixes #35
=> fix(scalar): enable back optimizations around scalar_sqrt_reciprocal for VS2019

CHANGELOG.md, appveyor.yml, includes/rtm/impl/detect_arch.h, sonar-project.properties
NEON isn't always enabled and it can cause compilation failures.
=> fix(core): avoid enabling NEON when just __arm__ is present

tools/bench/sources/bench_scalar_sin.cpp
Otherwise compilation error "error: unused variable 'constants3_'" occurs:
```
/mnt/c/Work/projects/rtm/tools/bench/sources/bench_scalar_sin.cpp:103:36: error: unused variable 'constants3_' [-Werror,-Wunused-const-variable]
alignas(64) static constexpr float constants3_[12] =
^
1 error generated.
```
=> fix: declare variable 'constants3_' only if RTM_NEON64_INTRINSICS macro defined

cmake/CMakeCompiler.cmake
You state [in README](https://github.com/nfrechette/rtm#supported-platforms)  that `Windows VS2019 with clang9 x86 and x64` is a supported platform. However, the attempt to compile the _benchmark_ with it results in the following error:
```
[ 43%] Building CXX object tools/bench/main_generic/CMakeFiles/rtm_bench.dir/__/sources/bench_quat_conjugate.cpp.obj
clang-cl: error: argument unused during compilation: '/MP' [-Werror,-Wunused-command-line-argument]
NMAKE : fatal error U1077: 'C:\PROGRA~1\LLVM\bin\clang-cl.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual …
```
=> build: disable /MP option on Windows for compilers other than Microsoft Visual C++

tests/main_generic/CMakeLists.txt
You state [in README](https://github.com/nfrechette/rtm#supported-platforms)  that `Windows VS2019 with clang9 x86 and x64` is a supported platform. However, the attempt to compile the _tests_ with it results in the following error:
```
[  0%] Building CXX object tests/main_generic/CMakeFiles/rtm_unit_tests.dir/__/sources/test_constants.cpp.obj
In file included from C:\Work\projects\rtm\tests\sources\test_constants.cpp:28:
In file included from C:\Work\projects\rtm\tests\main_generic\..\..\includes\rtm/scalarf.h:29:
In file included from C:\Work\projects\rtm\tests\main_generic\..\..\includes\rtm/macros.h:27:
In file included from C:\Work\projects\rtm\tests\main_generic\..\..\includes\rtm/math.h:115:
C:\Work\projects\rtm\tests\main_generic\..\..\includes\rtm/impl/error.h(140,6): error: …
```
=> build: enable exceptions for clang-cl

includes/rtm/impl/detect_features.h, includes/rtm/packing/quatf.h
Clang 14 started fusing separate mul/sub instructions which impacts
accuracy. Switching to intrinsics to ensure consistent results across
versions and tool chains.
=> fix(quat): ensure deterministic output on ARM64

includes/rtm/vector4f.h, tools/bench/sources/bench_vector_round_bankers.cpp, tools/bench/sources/bench_vector_round_symmetric.cpp
These are follow-up changes to PR #126 and issue #4. 
Tested with `aarch64-linux-gnu-gcc` and `arm-linux-gnueabihf-gcc` cross compilers, `qemu-aarch64` and `qemu-arm` CPU emulators, WSL2 on Windows 11.
- There is [vsetq_lane_f32](https://developer.arm.com/architectures/instruction-sets/intrinsics/vsetq_lane_f32) intrinsic for ARM64 to move an element from one vector to another. It was replaced with a combination of `vgetq_lane_f32` and `vsetq_lane_f32` intrinsics for compatibility with ARM, they shouldn't be this different according to [Godbolt](https://godbolt.org/z/oYodc78jP). But if necessary, a portable wrapper can be easily implemented.
- There is a common scenario when low/high doublewords of two vectors are combined together. However, I can't find appropriate intrinsic without …
=> feat: optimize vector_mix with NEON

includes/rtm/scalarf.h
Hello @nfrechette, constant parameter declaration may have been missed, judging by typedef in headers.
=> refactor(scalar): defining param as const by renaming it to scalarf_arg0

includes/rtm/impl/compiler_utils.h, tests/sources/test_vector4_impl.h
It can hurt determinism with little to no performance gain due to the high level of hand tuned optimizations.
=> fix: disable fast math with GCC

docs/types_supported.md, includes/rtm/impl/detect_compiler.h, includes/rtm/impl/qvs_common.h, includes/rtm/impl/type_args.h, includes/rtm/matrix3x4d.h, includes/rtm/matrix3x4f.h, includes/rtm/qvsd.h, includes/rtm/qvsf.h, includes/rtm/type_traits.h, includes/rtm/types.h, tests/sources/test_matrix3x3_impl.h, tests/sources/test_matrix3x4.cpp, tests/sources/test_qvs.cpp
A quat-vector type with uniform scalar scale is common in gamedev as it is fast, compact, and doesn't have the complexity of non-uniform scaling.
=> feat: impl qvs support

includes/rtm/quatd.h, includes/rtm/quatf.h, includes/rtm/scalard.h, includes/rtm/scalarf.h, includes/rtm/vector4d.h, includes/rtm/vector4f.h
Some of the header files are currently missing includes for the standard library functions and symbols they use.
I checked and updated all headers containing `std::` in their code.
This was causing a compilation error in an update to the Conan Center recipe here: https://github.com/conan-io/conan-center-index/pull/18230/files#diff-b483045c4a1cf08ae44bfc8475f303a8ed7eeea161937bec03ef83698be21f1cR1-R2
=> fix: add missing std includes

includes/rtm/math.h
Can cause compilation failure when SSE3 is enabled without SSE 4.1
=> fix: add missing SSE3 header

includes/rtm/impl/mask_common.h
=> fix(mask): narrow codegen hack to VS2017 and earlier

includes/rtm/impl/memory_utils.h
fix: usage of std::numeric_limits<DstType>::max() in memory_utils.h conflicted with minwindef.h under some circumstances
Hi, 
I use rtm in my personal project. Somehow I include the "minwindef.h" file (actually I don't know where it's included, maybe it's included by some third-party library I am using) and when I build project on Windows, an error happen:
```
0>memory_utils.h(208): Warning C4003 : 类函数宏的调用“max”参数不足 // means that number of parameters not correct when calling macro max
0>memory_utils.h(208): Error C1075 fatal: “{”: 未找到匹配令牌
```
Line 208:
`return uint64_t(input) <= uint64_t((std::numeric_limits<DstType>::max());` 
I jump to source code of max and it turns out to be in minwindef.h:
```
#ifndef max
#define max(a,b)            (((a) > (b)) ? (a) : (b))
#endif
```
With google …
=> fix: std::numeric_limits::max() in memory_utils.h conflicted with minwindef.h

includes/rtm/scalarf.h, includes/rtm/vector4d.h, includes/rtm/vector4f.h, tests/sources/test_vector4_impl.h
=> feat: add vector_sqrt_reciprocal
